### PR TITLE
Show methods take arrays

### PR DESCRIPTION
**Pull request by dvnstrcklnd**
Make show methods note, check, and bullet accept arrays of strings as an argument. Produces the same display as calling the method once on each element of the array.

This is useful for creating standard interfaces to things with differently complicated sets of instructions.

### CODE REVIEW

**Comment by dvnstrcklnd** [comment]
I have not tested this in the app, but it produces the correct behavior in this script:
```ruby
class ShowBlock
  attr_reader :parts
​
  def initialize()
    @parts = []
  end
​
  # Put the string s in a smaller font on the page. Often called several times.
  # If an array of strings is passed, then a bullet is made for each element of the array.
  # @param str [String, Array<String]
  # @return [void]
  def note(str)
    [*str].each { |s| @parts.push(note: s) }
  end
​
    # Put the string s on the page, with a bullet in front of it, as in a bullet list.
    # If an array of strings is passed, then a bullet is made for each element of the array.
    # @param str [String, Array<String]
    # @return [void]
    def bullet(str)
      [*str].each { |s| @parts.push(bullet: s) }
    end
end
​
​
a = ShowBlock.new()
puts a.parts.to_s
​
str = "foo"
a.note(str)
puts a.parts.to_s
​
str = ["bar", "baz"]
a.bullet(str)
puts a.parts.to_s
```

**Comment by bjkeller** [comment]
you guys and your underscores

**Comment by dvnstrcklnd** [comment]
huh?

**Comment by bjkeller** [comment]
(branch names using underscores.)

Making several notes with a method named `note` seems a conceptual stretch to me.  Other than Ruby lets you do it, is there a reason to overload the method instead of making a new one named `notes`?

**Comment by dvnstrcklnd** [comment]
What should I use?

I don't think it's a conceptual stretch at all. The method describes the
formatting, not the number of elements. It's just saying "format these
elements as a series of notes" and "format these elements as a series of
bullets" etc. without knowing how many elements. That's not exactly
armageddon.

It becomes a lot less convenient if the protocol developer has to worry
about which method to call.

**Comment by dvnstrcklnd** [comment]
I'd also argue that what's actually conceptually weird is thinking that
people usually want to make just one bullet (or note or checkbox). In
practice, I believe that these methods are usually called multiple times in
a row. It makes more sense to just treat a series of them as a unified
layout element.

**Comment by bjkeller** [comment]
Overloading `note` this way requires knowing that the method has this `each` behavior when passed an array. You might find this natural, but other people could reasonably assume a different implementation. For instance, that `note object` is interpreted as `note object.to_s`, or that, when passing an array, `note [s_1, ..., s_n]` could indicate a multi-line note with each `s_i` indicating a line.  What you have proposed is consistent with Ruby `puts`, there are whole blog posts explaining the difference between `puts` and `print` because the design choices made are confusing.  It's better to avoid situations where you have to write documentation that says "it behaves like this, unless that".

I would use something like `add_notes` instead, and either make it take variable arguments or an array, but not both.

**Comment by bjkeller** [comment]
I added specs for note, but just stubs for the other methods.

**Pull request merged**
