### PR TITLE
Dialogs in Sample Page

### PR DESCRIPTION
**Pull request by bjkeller**

### CODE REVIEW

**Comment by bjkeller** [comment]
@lekhacminhphuong This is a good start.  There are some things I'd like you to look at:

1. The dialog should not affect the Sample page unless `Save` is clicked.  Right now, if you open the  dialog and then click `Cancel`, the Sample page changes to say `Unsaved Samples`.
2. The dialog should close when `Save` is clicked.

There are some other details we should look at, but it would be good to get the basic behavior straightened out first.

**Comment by bjkeller** [comment]
This looks even better, but there are still a couple of things.
1. The messages and errors don't go away
2. Use the blue button to indicate what is the reasonable action to take at any given point. So, it should never be that both cancel and save buttons are blue at the same time.  Maybe keep Cancel blue until the project is given.

there is more, but I'll try to take a look next week.

**Comment by lekhacminhphuong** [comment]
> This looks even better, but there are still a couple of things.
> 
> 1. The messages and errors don't go away
> 2. Use the blue button to indicate what is the reasonable action to take at any given point. So, it should never be that both cancel and save buttons are blue at the same time.  Maybe keep Cancel blue until the project is given.
> 
> there is more, but I'll try to take a look next week.

**Comment by lekhacminhphuong** [comment]
Hi Ben,
I just tried to comment on your feedback, but I got an accident in closing this pull request.

**Comment by bjkeller** [comment]
I think this is as far as we can push the work on the dialog without affecting the rest of the page.

So, I created another branch named 
[update-sample-page](https://github.com/klavinslab/aquarium/tree/update-sample-page) 
and merged this branch into it.

Closing this PR.

**Pull request closed without merging**
